version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      - UPDATE=0
      - ENVIRONMENT
      - SECRET_KEY_BASE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - EMAIL_CONFIRMATION
      - MULTI_TENANCY
    volumes:
      - .:/astuto
    ports:
      - "3000:3000"
    depends_on:
      - db
    
volumes:
  dbdata: